# Numpy

These exercises are designed to introduce NumPy, the fundamental package for scientific computing with Python. It includes tools for working with N-dimensional arrays, and common numeric computing tools.

This notebook is adapted from [the NumPy quickstart tutorial](https://numpy.org/devdocs/user/quickstart.html)


In [12]:
import numpy as np


## Introduction & Basics

NumPy’s main object is the **homogeneous multidimensional array** - the `ndarray`. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called **axes**.

For example, the array for the coordinates of a point in 3D space, `[1, 2, 1]`, has one axis. That axis has 3 elements in it, so we say it has a length of 3. The array `a` in the example below has 2 axes: the first of length 2, and the second of length 3.


In [ ]:
a = np.array([[1.0, 0.0, 0.0], [0.0, 1.0, 2.0]])  # create the array from a python list

print(a)  # the array
print(f"{a.shape=}")  # the 'shape' of the array
print(f"{a.ndim=}")  # the number of dimensions, or axes
print(f"{a.dtype.name=}")  # the type of the array elements
print(f"{a.itemsize=}")  # the size in bytes of each array element
print(f"{a.size=}")  # the total number of elements in the array
print(f"{type(a)=}")  # how python identifies the type


## Creating Arrays

You can create arrays by calling `np.array()` on a python list or tuple, as shown in the example above. There's a few other useful ones to know of, however:

- `np.zeros()` creates an array of all 0 with a specified shape
- `np.ones()` creates an array of all 1 with a specified shape
- `np.arange()` creates an array with a single axis, same as Python's built in `range()`
- `np.linspace()` creates an array with a given number of elements


In [ ]:
a1 = np.array([2, 3, 4])  # an array of type int64
a2 = np.array([1.2, 2.3, 3.4])  # an array of type float64

# you can also use the dtype= keyword argument to give it a type explicitly
a3 = np.array([[1, 2], [3, 4]], dtype=complex)

# a 3x4 matrix of zeros
zero = np.zeros((3, 4))

# a 2x3x4 array (3-d array) of ones
ones = np.ones((2, 3, 4))

# a range of numbers between 10 and 30 with a step size of 5
fives = np.arange(10, 30, 5)

# 100 numbers between 0 and 2*pi
np.linspace(0, 2 * np.pi, 100)


## Indexing, Slicing, Iterating

So we have arrays, but how do we get the elements out of them or do anything with them?
- You can **index** an array by passing some coordinates to get the element at that coordinate
- **Slicing** an array gives you a range of elements from an array
- Looping over an array to perform an operation on each element, or each sub-array, is called **iterating**

### Exercise 1.1

Write some code to generate the identity matrix for:

- 2x2
- 3x3
- NxN


In [ ]:
# your code here


### Exercise 1.1

Write a loop to add the two arrays `a` and `b`


In [13]:
a = np.arange(15).reshape(3, 5)
b = np.ones((3, 5))

# your code here


### Exercise 1.3

Write some code to perform matrix multiplication on the two arrays `D` and `C` (compute `CD`)


In [ ]:
C = np.array(([5, -7, 9], [-1, 4, 3], [11, 20, -4], [0, 17, -2]))
D = np.linspace(0,1,15).reshape(3,5)

# your code here

## Operations on Arrays

Fortunately for you, all of the things you just implemented manually above are not necessary, because numpy includes them by default!


You can think of a 1-dimensional `numpy` array as a vector, and we can use very compact code to perform *vector* mathematical operations on the entire array.

In [14]:
b1 = np.array([1, 2, 3])
print(b1)
print(b1 + 1)
print(b1 ** 2) # Remember ** is the power operator. This calculates b^2 for every number (b) stored in b1.

[1 2 3]
[2 3 4]
[1 4 9]


If the mathematical expression involves two (or more) arrays, then an element-by-element operation is performed

In [11]:
b1 = np.array([1, 2, 3])
b2 = np.array([4, 4, 6])
print(b1 + b2)
# The first element of b1 is added to the first element of b2, the second element of b1 is added to the second element of b2, etc.

[5 6 9]


Let us try to calculate the square root of all the numbers in `a1`

In [ ]:
from math import sqrt
a1 = np.array([1, 2, 3, 4 ])
sqrt(a1)

This gives an error.

Because `numpy` is not part of the standard Python library, the `sqrt` function provided by the `math` module does not know how to treat a `numpy` array of numbers. To do what we want we can use the `sqrt` function in `numpy` instead

In [ ]:
a1 = np.array([1, 2, 3, 4 ])
np.sqrt(a1)